### ISSUE TITLE
Modules not installed with setup file

### ISSUE THREAD

**Issue by xnand** [operatorequals/covertutils#12] opened 2017-09-12 14:07 UTC
I downloaded the last version and tried the bind tcp example, and it gave me errors about modules. I then tried importing the same in python2 interpreter:

`>>> from covertutils.handlers.basehandler import BaseHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named handlers.basehandler
`

I took a look at the installed modules:
`>>> print(covertutils.__file__)
/usr/lib/python2.7/site-packages/covertutils-0.3.1-py2.7.egg/covertutils/__init__.pyc`

and saw that actually very few things were installed. So I opened the setup.py file provided and added `find_packages` as a module to import and modified the `packages` argument of the setup function like this:

`packages=find_packages(),`

I am not practised with setuptools and this is the result of a 3 mins search, but now it works.
I don't know if it's a mistake or mine or whatever, just thought I might tell you...

**Comment by operatorequals** [comment] 2017-09-12 14:50
This looks like I overlooked something really big: _subpackages_...
I'll check it out tonight!

**Thank you for noticing!**

**Comment by operatorequals** [comment] 2017-09-13 10:27
Try to reproduce now (latest commit)!
I think I fixed it. It was a common _copy-paste_ failure!

**Comment by xnand** [comment] 2017-09-13 12:33
Yep, now it works. Thank you  😃

**Comment by operatorequals** [comment] 2017-09-16 08:47
Pushed version [0.3.2 to PyPI](https://pypi.python.org/pypi/covertutils)

Should work. If you test it through `pip install covertutils` and it works, please close the issue!

Thanks again!

**Comment by operatorequals** [comment] 2017-09-20 11:55
``` bash 
$ virtualenv issue_test
$ cd issue_test
$ ls
bin  include  lib  local  pip-selfcheck.json
$ source bin/activate
(issue_test) $ 
(issue_test) $ pip install covertutils
Collecting covertutils
  Downloading covertutils-0.3.2.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 106kB/s 
Building wheels for collected packages: covertutils
  Running setup.py bdist_wheel for covertutils ... done
  Stored in directory: /home/unused/.cache/pip/wheels/ee/a5/76/af12a761d003e41fed3375d5d2db0d96e0425cc763d09b86a9
Successfully built covertutils
Installing collected packages: covertutils
Successfully installed covertutils-0.3.2
(issue_test) $ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import covertutils.handlers
>>> ^C
(issue_test) $ wget https://raw.githubusercontent.com/operatorequals/covertutils/master/examples/tcp_reverse_agent.py
--2017-09-17 12:31:46--  https://raw.githubusercontent.com/operatorequals/covertutils/master/examples/tcp_reverse_agent.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1112 (1.1K) [text/plain]
Saving to: ‘tcp_reverse_agent.py’

tcp_reverse_agent.py      100%[=====================================>]   1.09K  --.-KB/s    in 0s      

2017-09-17 12:31:47 (29.6 MB/s) - ‘tcp_reverse_agent.py’ saved [1112/1112]

(issue_test) $ python tcp_reverse_agent.py 
Traceback (most recent call last):
  File "tcp_reverse_agent.py", line 12, in <module>
    addr = sys.argv[1], int(sys.argv[2])
IndexError: list index out of range

```
No `ImportError`!
Seems working for me!

Closing the issue!

**Closed by operatorequals** 2017-09-20 11:55 UTC

**Comment by xnand** [comment] 2017-09-20 12:18
Oh sorry, I didn't see the mail :satisfied: Yep, it's working for me too
